#!/usr/bin/env python3
"""Validate/render the roadmap; explicitly sync its issues with --sync.

GitHub writes require --sync. Rendering and checking are local. Existing task IDs
are discovered before creation, so an interrupted sync can be resumed safely.
This tool never closes issues automatically: completion needs reviewed evidence.
"""
import argparse
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/roadmap.json"
OUTPUT = ROOT / "docs/ROADMAP.md"
LABELS = {
    "documentation": ("0075ca", "Documentation and public product information"),
    "roadmap": ("5319e7", "Accepted delivery roadmap task"),
    "release": ("1d76db", "Release preparation and publication"),
    "correctness": ("b60205", "Scientific or resource correctness"),
    "onboarding": ("0e8a16", "Researcher and builder first useful result"),
    "cohort": ("006b75", "Verified local cohort reanalysis"),
    "deferred": ("eeeeee", "Outside the current delivery sequence"),
}


def validate(data):
    tasks = data["tasks"]
    ids = [task["id"] for task in tasks]
    if len(ids) != len(set(ids)):
        raise ValueError("duplicate roadmap task ID")
    numbers = [task["issue_number"] for task in tasks if task.get("issue_number")]
    urls = [task["issue_url"] for task in tasks if task.get("issue_url")]
    if len(numbers) != len(set(numbers)) or len(urls) != len(set(urls)):
        raise ValueError("duplicate roadmap issue mapping")
    by_id = {task["id"]: task for task in tasks}
    for task in tasks:
        if not re.fullmatch(r"[GDRUCF][0-9]{2}", task["id"]):
            raise ValueError("invalid task ID")
        if task["status"] not in ("planned", "in-progress", "implemented", "blocked", "complete"):
            raise ValueError("invalid task status")
        if not task["title"] or not task["acceptance"] or not task["owner"]:
            raise ValueError("task needs title, acceptance and owner")
        if task["status"] == "complete" and not task["evidence"]:
            raise ValueError("completion needs evidence")
        if any(dep not in by_id for dep in task["depends_on"]):
            raise ValueError("unknown dependency")
        if task.get("issue_url") != (f"https://github.com/{data['repository']}/issues/{task['issue_number']}"
                                     if task.get("issue_number") else None):
            raise ValueError("issue URL does not match repository and number")
    visited, active = set(), set()
    def walk(key):
        if key in active:
            raise ValueError("dependency cycle")
        if key in visited:
            return
        active.add(key)
        for dep in by_id[key]["depends_on"]:
            walk(dep)
        active.remove(key)
        visited.add(key)
    for key in ids:
        walk(key)


def render(data):
    lines = ["# Rosalind delivery roadmap", "",
             "<!-- Generated by scripts/roadmap.py --render from docs/roadmap.json. -->", "",
             data["objective"], "",
             "Lead workflow: candidate-SNV reanalysis. Documentation is GitHub-first; "
             "cohort v1 is local CLI/Python over immutable verified datasets. "
             "Keep 0.5 release closure separate from cohort APIs on an isolated next-minor development line; "
             "development need not wait for stable publication or participant recruitment.", "",
             "[Start here](index.md) · [Capability and release status](implementation-status.md) · "
             "[Adoption evidence](adoption-validation.md)", "",
             "## How to use this backlog", "",
             "Task status describes delivery, not biological validation. **Implemented** means code/documentation "
             "exists but remaining acceptance or publication gates have not passed. **Complete** requires linked "
             "acceptance evidence. External participants, credentials and elapsed-time gates cannot be simulated by CI.", "",
             "Update `docs/roadmap.json`, then run `python3 scripts/roadmap.py --render --check`. "
             "Use `--sync` only when GitHub issue updates are intended. The sync preserves existing issue "
             "history and never auto-closes a task.", "",
             "## Delivery order and gates", "",
             "1. Reconcile public claims and close CRAM correctness/validation work.",
             "2. Complete documentation, executable onboarding and publication prerequisites in parallel.",
             "3. Publish an immutable RC; observe the seven-day soak and required technical evidence.",
             "4. Publish stable only after the existing policy and fresh registry-only installation checks pass.",
             "5. In parallel, build cohort snapshots and candidate queries on the isolated next-minor line.",
             "6. Use independent repeat usage to justify paired comparisons and later molecular feasibility.", "",
             "Independent persona feedback, design-partner recruitment and the 30-day return target measure adoption; "
             "they are not implementation or publication prerequisites. Validate actual submitted feedback and "
             "report absent evidence honestly. Explicit unresolved release-blocking defects remain technical blockers. "
             "Keep cohort work out of the frozen 0.5 candidate; next-minor "
             "features retain their technical, scientific and compatibility acceptance checks. "
             "F02/F03 remain product-review decisions requiring a specified useful task and validation plan.", ""]
    for prefix, title in data["milestones"].items():
        lines += [f"## {title}", ""]
        for task in data["tasks"]:
            if not task["id"].startswith(prefix):
                continue
            key = task["id"]
            label = f"[{key}]({task['issue_url']})" if task.get("issue_url") else key
            lines += [f"- [{'x' if task['status'] == 'complete' else ' '}] **{label} — {task['title']}**", "",
                      f"  Status: **{task['status']}**. Owner: {task['owner']}. "
                      f"Dependencies: {', '.join(task['depends_on']) or 'none'}.", "",
                      f"  Done when: {task['acceptance']}", ""]
            if task.get("blocker"):
                lines += [f"  Remaining gate: {task['blocker']}", ""]
            if task["evidence"]:
                lines += ["  Evidence: " + " · ".join(task["evidence"]), ""]
    lines += ["## Scientific and implementation boundaries", "",
              "Preserve scientific output across admitted resource schedules, explicit missingness and denominators, "
              "transactional artifacts, and historical receipt/dataset verification. A receipt is not proof of "
              "authorship or biological accuracy. Read evidence cannot reconstruct excluded observations or UMI families.", "",
              "Cohort snapshots reference intact verified leaf datasets; do not weaken same-source reuse identities "
              "to compare samples. Saved queries never implicitly reopen original alignments. Explicit extensions "
              "verify source identity and publish a new snapshot last. Strict missing-locus refusal is the default; "
              "partial mode carries missingness rather than fabricated zeros.", "",
              "Deferred: a web dashboard, distributed/cloud execution, automatic source discovery, storage garbage "
              "collection, broad modalities, production calling, and universal low-memory computation. "
              "Keep current supported platforms and the open, portable artifact model.", "",
              "## Acceptance scorecard", "",
              "| Measure | Acceptance |", "|---|---|",
              "| Researcher onboarding | Three non-authors complete a verified small-data task; target under 30 minutes, recording assistance and failures |",
              "| Builders and workflows | One independent analyzer and one integrated workflow complete useful tasks |",
              "| Cohort use | Two teams answer recurring candidate questions with independently checked results |",
              "| Return use | Two teams perform meaningful work after at least 30 days; unknown outcomes remain unknown |",
              "| Correctness | Exact supported integer observations/summaries and byte-identical admitted execution/replay |",
              "| Reuse economics | Include initial import/materialization, duplicated storage, hashing, verification and subsequent queries |", ""]
    return "\n".join(lines)


def gh_json(args, payload=None):
    command = ["gh", *args]
    text = None
    if payload is not None:
        command += ["--input", "-"]
        text = json.dumps(payload)
    result = subprocess.run(command, input=text, text=True, check=True, capture_output=True)
    return json.loads(result.stdout) if result.stdout.strip() else None


def sync(data):
    repo = data["repository"]
    # Resolve and validate every mapping before any remote writes.
    issues = gh_json(["issue", "list", "--repo", repo, "--state", "all", "--limit", "1000",
                      "--json", "number,title,url"])
    existing = {}
    by_number = {issue["number"]: issue for issue in issues}
    for issue in issues:
        match = re.match(r"\[([GDRUCF][0-9]{2})\]", issue["title"])
        if match:
            if match[1] in existing:
                raise ValueError(f"duplicate existing task {match[1]}")
            existing[match[1]] = issue["number"]
    reuse = {"R06": 53, "R07": 55}
    resolved = {}
    for task in data["tasks"]:
        key = task["id"]
        saved, discovered = task.get("issue_number"), existing.get(key)
        if saved and discovered and saved != discovered:
            raise ValueError(f"conflicting issue mapping for {key}")
        number = saved or discovered or reuse.get(key)
        if number:
            if number not in by_number:
                raise ValueError(f"issue #{number} missing from inventory; refusing unverified mapping")
            marker = re.match(r"\[([GDRUCF][0-9]{2})\]", by_number[number]["title"])
            if marker and marker[1] != key:
                raise ValueError(f"issue #{number} belongs to {marker[1]}, not {key}")
            if not marker and reuse.get(key) != number:
                raise ValueError(f"issue #{number} has no matching roadmap ID")
        resolved[key] = number
    assigned = [number for number in resolved.values() if number]
    if len(assigned) != len(set(assigned)):
        raise ValueError("multiple tasks resolve to one issue")
    for name, (color, description) in LABELS.items():
        subprocess.run(["gh", "label", "create", name, "--repo", repo, "--color", color,
                        "--description", description, "--force"], check=True, capture_output=True)
    milestones = gh_json(["api", f"repos/{repo}/milestones?state=all&per_page=100"])
    numbers = {item["title"]: item["number"] for item in milestones}
    for title in data["milestones"].values():
        if title not in numbers:
            result = gh_json(["api", f"repos/{repo}/milestones", "--method", "POST"],
                             {"title": title, "description": data["objective"]})
            numbers[title] = result["number"]
    for task in data["tasks"]:
        key = task["id"]
        number = resolved[key]
        dependencies = ", ".join(task["depends_on"]) or "none"
        body = (f"## Outcome\n\n{task['title']}\n\n"
                f"Part of the [accepted delivery roadmap](https://github.com/{repo}/blob/main/docs/ROADMAP.md). "
                "The task remains open until the acceptance evidence is reviewed.\n\n"
                f"## Acceptance\n\n{task['acceptance']}\n\n"
                f"## Dependencies and ownership\n\n- Dependencies: {dependencies}\n"
                f"- Owner: {task['owner']}\n- Delivery status: {task['status']}\n")
        if task.get("blocker"):
            body += f"\n## Remaining gate\n\n{task['blocker']}\n"
        if task["evidence"]:
            body += "\n## Evidence\n\n" + "\n".join(f"- {item}" for item in task["evidence"]) + "\n"
        labels = ["roadmap", {"G": "documentation", "D": "onboarding", "R": "release",
                               "U": "onboarding", "C": "cohort", "F": "deferred"}[key[0]]]
        if key == "R01":
            labels.append("correctness")
        payload = {"title": f"[{key}] {task['title']}", "body": body,
                   "milestone": numbers[data["milestones"][key[0]]], "labels": labels,
                   "assignees": [repo.split('/')[0]]}
        endpoint = f"repos/{repo}/issues" + (f"/{number}" if number else "")
        if number:
            current = gh_json(["api", endpoint])
            payload["labels"] = sorted(set(labels) | {item["name"] for item in current["labels"]})
            payload["assignees"] = [item["login"] for item in current["assignees"]] or payload["assignees"]
        result = gh_json(["api", endpoint, "--method", "PATCH" if number else "POST"], payload)
        task["issue_number"], task["issue_url"] = result["number"], result["html_url"]
        SOURCE.write_text(json.dumps(data, indent=2) + "\n")
    # Once numbers are known, link dependencies without creating duplicate issues.
    index = {task["id"]: task for task in data["tasks"]}
    for task in data["tasks"]:
        if not task["depends_on"]:
            continue
        issue = gh_json(["api", f"repos/{repo}/issues/{task['issue_number']}"])
        linked = ", ".join(f"[{key}]({index[key]['issue_url']})" for key in task["depends_on"])
        body = re.sub(r"- Dependencies: .*", f"- Dependencies: {linked}", issue["body"])
        gh_json(["api", f"repos/{repo}/issues/{task['issue_number']}", "--method", "PATCH"], {"body": body})
    print(f"Synchronized {len(data['tasks'])} roadmap tasks and {len(numbers)} milestones")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--render", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--sync", action="store_true")
    args = parser.parse_args()
    data = json.loads(SOURCE.read_text())
    validate(data)
    if args.sync:
        sync(data)
    expected = render(data)
    if args.render or args.sync:
        OUTPUT.write_text(expected)
    if args.check and (not OUTPUT.exists() or OUTPUT.read_text() != expected):
        raise SystemExit("ROADMAP.md is stale; run scripts/roadmap.py --render")
    print(f"Validated {len(data['tasks'])} tasks")


if __name__ == "__main__":
    main()
